  server:
  port: 8079

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscheck
          uri: lb://api-check
          predicates:
            - Path=/api/v1/check/**
        - id: msprovider
          uri: lb://api-provider
          predicates:
            - Path=/api/v1/provider/**
        - id: mscustomer
          uri: lb://api-customer
          predicates:
            - Path=/api/v1/customer/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
